name: cleanup-pr

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - feature/*

env:
  TARGET_ACCOUNT_ID: ${{ secrets.DEV_ACCOUNT_ID }}
  APPLICATION_NAME: mbarneyme

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  get_short_ref:
    runs-on: ubuntu-latest
    outputs:
      short_ref: ${{ steps.short_ref_job.outputs.short_ref }}
    steps:
      - id: short_ref_job
        name: Testing
        run: |
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          export SHORT_REF=$(echo ${GITHUB_HEAD_REF/feature\//} | cut -c -16)
          echo "SHORT_REF: ${SHORT_REF}"
          echo "short_ref=${SHORT_REF}" >> $GITHUB_OUTPUT
  cleanup_pr:
    runs-on: ubuntu-latest
    container: ghcr.io/mbarneyjr/ci-docker-image:latest
    needs: get_short_ref
    env:
      ENVIRONMENT_NAME: ${{ needs.get_short_ref.outputs.short_ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ env.TARGET_ACCOUNT_ID }}:role/github-actions
          role-session-name: GitHubActions-${{ github.run_id }}
      - name: Delete environment
        run: |
          make delete
